### ISSUE TITLE
Update repo name to awesome-hackathon-starters

### ISSUE THREAD

**Issue by xasos** [geekcamp-ph/awesome-hackathon-starters#10]
Just in the spirit of GitHub lists, updating the title to 'awesome-hackathon-starters' :D

**Comment by katgironpe** [comment]
@xasos Might conflict with https://github.com/egoist/awesome-starter

**Comment by katgironpe** [comment]
But yes I can do that now. ;)

**Comment by katgironpe** [comment]
Done!

**Comment by xasos** [comment]
thanks! :)
